// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"Plugin Analysis Common Base","parameters":{}},
{"name":"ExtraWindow","status":true,"description":"Extra Window Display Per Scene Plugin","parameters":{"WindowList":"[\"{\\\"SceneName\\\":\\\"Scene_Map\\\",\\\"x\\\":\\\"0\\\",\\\"y\\\":\\\"0\\\",\\\"width\\\":\\\"200\\\",\\\"height\\\":\\\"0\\\",\\\"LineHeight\\\":\\\"36\\\",\\\"Text\\\":\\\"Value: \\\\\\\\V[1]\\\",\\\"FontSize\\\":\\\"0\\\",\\\"WindowSkin\\\":\\\"\\\",\\\"SwitchId\\\":\\\"0\\\",\\\"ShowOpenAnimation\\\":\\\"true\\\"}\"]"}}
];
